### ISSUE TITLE
Training memory

### ISSUE THREAD

**Issue by qilinli** [isht7/pytorch-deeplab-resnet#21]
@isht7 Thanks for sharing the code. I am wondering is there a simple way to reduce the memory required for training, as it is just a bit of more than the card (1080ti, 11G) I have.

**Comment by isht7** [comment]
Set scale to 1.0 [here.](https://github.com/isht7/pytorch-deeplab-resnet/blob/master/train.py#L90) instead of the current randomly selected value. This disables the scale augmentation but should fit in your GPU after that. Let me know what happens when you do this. This will affect performance by about 1-2% mIoU.

**Comment by qilinli** [comment]
@isht7 Thanks for your advice. I changed the max scale to 1.1 and get the validation score 72.3%. Compared to yours 72.4% it seems no harm. The GPU memory reduced to roughly 10.7G.
